name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Docker image
        run: |
          docker build --build-arg VERSION=1.0.${{ github.run_number }} -t myapp:$${{ github.run_number }} .
          docker build -t myapp:latest .

      - name: Push Docker image
        run: |
          docker push myapp:${{ github.run_number }}
          docker push myapp:latest


      #- name: Deploy image
        # Add your deployment steps here, such as deploying to Kubernetes or a server
      
