name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          build-args: VERSION=1.0.${{ github.run_number }}
          context: .
          push: true
          tags: test-rep:githubapp-${{ github.run_number }}
        env:
          IMAGE_NAME: githubapp
          DOCKER_REPO: strukovsergei/test-rep
      #- name: Deploy image
        # Add your deployment steps here, such as deploying to Kubernetes or a server
      
