name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Docker image
        run: |
          docker build --build-arg VERSION=1.0.${{ github.run_number }} -t myapp:${{ github.run_number }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: strukovsergei/test-rep:myapp-${{ github.run_number }}

      #- name: Deploy image
        # Add your deployment steps here, such as deploying to Kubernetes or a server
      
