name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . 
          push: true
          tags: strukovsergei/test-rep:myapp-${{ github.run_number }}
          build-args: VERSION=1.0.${{ github.run_number }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #- name: Deploy image
        # Add your deployment steps here, such as deploying to Kubernetes or a server
      
