name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build JAR
        run: |
          # Your build command here
          mvn clean package
          mvn -B versions:set -DnewVersion=${{ github.event.release.tag_name }} -DgenerateBackupPoms=false

      - name: Build Docker image
        run: |
          docker build -t myapp:${{ steps.bump_version.outputs.new_version }} .
          docker build -t myapp:latest .

      - name: Push Docker image
        run: |
          docker push myapp:${{ steps.bump_version.outputs.new_version }}
          docker push myapp:latest


      #- name: Deploy image
        # Add your deployment steps here, such as deploying to Kubernetes or a server
      
